### PR TITLE
sqlccl: readonly queries over backups

### PR DESCRIPTION
**Pull request by danhhz**

### CODE REVIEW

**Comment by danhhz** [comment]
cc @knz wanna take a preliminary look? Especially:

- I'm not thrilled with how the tablename stuff worked out (especially how hardcoded it is that the three part name means a backup)
- how did we plan on representing a backup with some incrementals? i don't remember
- I also don't like how much this abuses the virtual table system. for example I had to use `keys.VirtualDescriptorID - 1` as the sentinel table id, because keys.VirtualDescriptorID triggers some behavior I didn't want (specifically AllNonDropIndexes returns no indexes). i think archival tables would have to be a more first class thing

**Comment by knz** [comment]
Yes, this is a very nice feature indeed, and I am delighted at how little code is needed to get there.

Here are some attention points that we need to iterate over:
- I am not entirely fond of the proposed SQL syntax; namely overloading the "." is making the name resolution code more complex, and I think it's already complex enough. What about extending the syntax for a table name with a new punctuation / keyword that adds an archive prefix, for example `:archive:[db.]table` and have the grammar parse the archive prefix separately from the qname and assign the ArchiveName in the tablename using a separate action. (we can bikeshed the precise syntax: what matters is to get the archive prefix out of the UnresolvedName)
- I do not feel qualified to evaluate the design of the CCL/non-CCL API you're introducing here, and the hijack of the KV reader. It feels ok but there may be some fine print which I'm not aware of. Perhaps Radu and/or Peter could chime in and review and/or suggest alternate reviewers.
- How does this behave with distsql?
- What do we get with mixed backup / non-backup sources? e.g. through an index join?

**Comment by knz** [comment]
To answer your questions:
- I do not remember our discussion about incrementals either, but perhaps that'd be an extension to the archive prefix in the syntax?
- let's talk again about the virtual table system. That needs a refactoring but I wanted to delay that discussion until post-1.0.

**Comment by danhhz** [comment]
Superceded by https://github.com/cockroachdb/cockroach/pull/20664

**Pull request closed without merging**
